# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73fc032911c60623d96edfec39ae96be1ed5d052d529d74a858ac8d66bddfedbe92c654a29e9ea0dc9c5ecb79eb00ffd1996c14741de4211fcf3d8b79363aa6

test:
  secret_key_base: 2b0ab5120b0ee004bc1d141e9be4ccabb4ea0289a9c46d567a1efbca7fcee31742518b6386e2e73988f582ff818bef8d22b34d39694403e6d32ff9679d6170fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
